-- LunaVisual Supabase setup
-- Run this file once in Supabase Dashboard -> SQL Editor.
-- Passwords are NOT stored in public tables. Create the owner account in Supabase Auth.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  mc_nickname text,
  avatar_url text,
  hwid text,
  subscription_active boolean not null default false,
  subscription_until text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists mc_nickname text;
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists hwid text;
alter table public.profiles add column if not exists subscription_active boolean not null default false;
alter table public.profiles add column if not exists subscription_until text;
alter table public.profiles add column if not exists is_admin boolean not null default false;
alter table public.profiles add column if not exists created_at timestamptz not null default now();
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create table if not exists public.license_keys (
  id bigint generated by default as identity primary key,
  code text not null unique,
  duration_days integer,
  is_used boolean not null default false,
  used_by text,
  used_by_user_id uuid references auth.users(id) on delete set null,
  used_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.license_keys add column if not exists duration_days integer;
alter table public.license_keys add column if not exists is_used boolean not null default false;
alter table public.license_keys add column if not exists used_by text;
alter table public.license_keys add column if not exists used_by_user_id uuid references auth.users(id) on delete set null;
alter table public.license_keys add column if not exists used_at timestamptz;
alter table public.license_keys add column if not exists created_by uuid references auth.users(id) on delete set null;
alter table public.license_keys add column if not exists created_at timestamptz not null default now();

create index if not exists license_keys_used_idx on public.license_keys(is_used, created_at desc);
create index if not exists license_keys_user_idx on public.license_keys(used_by_user_id);
create index if not exists profiles_email_idx on public.profiles(lower(email));


-- ---------------------------------------------------------------------------
-- Abuse / application-layer DDoS protection for Supabase RPC calls.
-- This does not replace a CDN/WAF for network-layer DDoS, but it prevents a
-- logged-in account from hammering expensive LunaVisual RPC functions.
-- ---------------------------------------------------------------------------
create table if not exists public.rpc_rate_limits (
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  window_started_at timestamptz not null default now(),
  request_count integer not null default 0,
  primary key (user_id, action)
);

alter table public.rpc_rate_limits enable row level security;
revoke all on table public.rpc_rate_limits from anon, authenticated;

create or replace function public.check_lunavisual_rate_limit(
  p_action text,
  p_max_requests integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_now timestamptz := clock_timestamp();
  v_row public.rpc_rate_limits%rowtype;
begin
  if v_uid is null then
    raise exception 'login_required';
  end if;
  if p_action is null or length(trim(p_action)) = 0 then
    raise exception 'invalid_rate_limit_action';
  end if;
  if p_max_requests < 1 or p_window_seconds < 1 then
    raise exception 'invalid_rate_limit_config';
  end if;

  insert into public.rpc_rate_limits(user_id, action, window_started_at, request_count)
  values (v_uid, p_action, v_now, 1)
  on conflict (user_id, action) do nothing;

  select * into v_row
  from public.rpc_rate_limits
  where user_id = v_uid and action = p_action
  for update;

  if v_row.window_started_at + make_interval(secs => p_window_seconds) <= v_now then
    update public.rpc_rate_limits
    set window_started_at = v_now,
        request_count = 1
    where user_id = v_uid and action = p_action;
    return true;
  end if;

  if v_row.request_count >= p_max_requests then
    return false;
  end if;

  update public.rpc_rate_limits
  set request_count = request_count + 1
  where user_id = v_uid and action = p_action;

  return true;
end;
$$;

revoke all on function public.check_lunavisual_rate_limit(text, integer, integer) from public;
grant execute on function public.check_lunavisual_rate_limit(text, integer, integer) to authenticated;

create or replace function public.is_lunavisual_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    lower(coalesce(auth.jwt() ->> 'email', '')) = 'bobretor10@gmail.com'
    or exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_admin = true
    );
$$;

grant execute on function public.is_lunavisual_admin() to authenticated;

create or replace function public.handle_lunavisual_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, mc_nickname, is_admin)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'mc_nickname', split_part(new.email, '@', 1)),
    lower(coalesce(new.email, '')) = 'bobretor10@gmail.com'
  )
  on conflict (id) do update set
    email = excluded.email,
    mc_nickname = coalesce(public.profiles.mc_nickname, excluded.mc_nickname),
    is_admin = public.profiles.is_admin or excluded.is_admin,
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_lunavisual on auth.users;
create trigger on_auth_user_created_lunavisual
after insert or update of email, raw_user_meta_data on auth.users
for each row execute procedure public.handle_lunavisual_new_user();

-- Promote the owner if the Auth account already exists.
insert into public.profiles (id, email, mc_nickname, avatar_url, is_admin)
select id, email, 'Glav-Luna', 'project-avatar.png', true
from auth.users
where lower(email) = 'bobretor10@gmail.com'
on conflict (id) do update set
  email = excluded.email,
  mc_nickname = 'Glav-Luna',
  avatar_url = 'project-avatar.png',
  is_admin = true,
  updated_at = now();


-- IMPORTANT: key generation is tied only to Supabase WEBSITE authentication.
-- The LunaVisual launcher intentionally has no separate registration requirement.
-- Users register on the website; generated keys can then be entered in the launcher.
create or replace function public.generate_lunavisual_keys(
  p_count integer,
  p_duration_days integer default 30
)
returns setof public.license_keys
language plpgsql
security definer
set search_path = public
as $$
declare
  i integer;
  v_code text;
  v_row public.license_keys%rowtype;
begin
  if not public.is_lunavisual_admin() then
    raise exception 'admin_required';
  end if;
  if not public.check_lunavisual_rate_limit('generate_keys', 12, 60) then
    raise exception 'rate_limited';
  end if;
  if p_count is null or p_count < 1 or p_count > 1000 then
    raise exception 'count_must_be_between_1_and_1000_per_batch';
  end if;
  if p_duration_days is null or p_duration_days < 1 then
    raise exception 'duration_must_be_positive';
  end if;

  for i in 1..p_count loop
    loop
      v_code := 'LUNAVISUALKEY-' ||
        lpad(floor(random()*10000)::int::text, 4, '0') || '-' ||
        lpad(floor(random()*10000)::int::text, 4, '0') || '-' ||
        lpad(floor(random()*10000)::int::text, 4, '0') || '-' ||
        lpad(floor(random()*10000)::int::text, 4, '0') || '-' ||
        lpad(floor(random()*10000)::int::text, 4, '0');
      begin
        insert into public.license_keys(code, duration_days, created_by)
        values (v_code, p_duration_days, auth.uid())
        returning * into v_row;
        exit;
      exception when unique_violation then
        -- collision: generate another code
      end;
    end loop;
    return next v_row;
  end loop;
end;
$$;

grant execute on function public.generate_lunavisual_keys(integer, integer) to authenticated;

create or replace function public.redeem_lunavisual_key(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  k public.license_keys%rowtype;
  u auth.users%rowtype;
  v_until timestamptz;
  v_until_text text;
  v_nick text;
begin
  if auth.uid() is null then
    raise exception 'login_required';
  end if;
  if not public.check_lunavisual_rate_limit('redeem_key', 10, 60) then
    return jsonb_build_object('ok', false, 'error', 'rate_limited');
  end if;

  select * into k
  from public.license_keys
  where upper(code) = upper(trim(p_code))
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'error', 'not_found');
  end if;
  if k.is_used then
    return jsonb_build_object('ok', false, 'error', 'used');
  end if;

  select * into u from auth.users where id = auth.uid();
  select coalesce(mc_nickname, split_part(coalesce(email, u.email), '@', 1))
    into v_nick from public.profiles where id = auth.uid();

  if k.duration_days >= 9000 then
    v_until_text := 'Навсегда (Lifetime)';
  else
    v_until := now() + make_interval(days => k.duration_days);
    v_until_text := 'до ' || to_char(v_until at time zone 'UTC', 'DD.MM.YYYY');
  end if;

  update public.license_keys
  set is_used = true,
      used_by = coalesce(v_nick, u.email),
      used_by_user_id = auth.uid(),
      used_at = now()
  where id = k.id;

  update public.profiles
  set subscription_active = true,
      subscription_until = v_until_text,
      updated_at = now()
  where id = auth.uid();

  return jsonb_build_object(
    'ok', true,
    'code', k.code,
    'duration_days', k.duration_days,
    'subscription_until', v_until_text
  );
end;
$$;

grant execute on function public.redeem_lunavisual_key(text) to authenticated;

create or replace function public.protect_lunavisual_profile_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() = old.id
     and not public.is_lunavisual_admin()
     and current_user <> 'postgres'
     and (new.subscription_active is distinct from old.subscription_active
          or new.subscription_until is distinct from old.subscription_until
          or new.is_admin is distinct from old.is_admin) then
    raise exception 'protected_profile_fields';
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists protect_lunavisual_profile_fields_trg on public.profiles;
create trigger protect_lunavisual_profile_fields_trg
before update on public.profiles
for each row execute procedure public.protect_lunavisual_profile_fields();


-- API for the LunaVisual launcher. The launcher signs in through Supabase Auth,
-- then calls this RPC to obtain only the current user's own license state.
create or replace function public.get_lunavisual_launcher_state()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  p public.profiles%rowtype;
  v_maintenance boolean;
begin
  if auth.uid() is null then
    raise exception 'login_required';
  end if;
  if not public.check_lunavisual_rate_limit('launcher_state', 120, 60) then
    raise exception 'rate_limited';
  end if;

  select * into p from public.profiles where id = auth.uid();
  if not found then
    raise exception 'profile_not_found';
  end if;

  select exists(select 1 from public.license_keys where code = 'MAINTENANCE_MODE')
    into v_maintenance;

  return jsonb_build_object(
    'user_id', p.id,
    'email', p.email,
    'nickname', p.mc_nickname,
    'hwid', p.hwid,
    'subscription_active', p.subscription_active,
    'subscription_until', p.subscription_until,
    'is_admin', public.is_lunavisual_admin(),
    'maintenance', v_maintenance
  );
end;
$$;

grant execute on function public.get_lunavisual_launcher_state() to authenticated;

alter table public.profiles enable row level security;
alter table public.license_keys enable row level security;

drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read on public.profiles for select to authenticated
using (id = auth.uid() or public.is_lunavisual_admin());

drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles for update to authenticated
using (id = auth.uid() or public.is_lunavisual_admin())
with check (id = auth.uid() or public.is_lunavisual_admin());

drop policy if exists profiles_admin_all on public.profiles;
create policy profiles_admin_all on public.profiles for all to authenticated
using (public.is_lunavisual_admin())
with check (public.is_lunavisual_admin());

drop policy if exists license_keys_admin_read on public.license_keys;
create policy license_keys_admin_read on public.license_keys for select to authenticated
using (public.is_lunavisual_admin());

drop policy if exists license_keys_admin_insert on public.license_keys;
create policy license_keys_admin_insert on public.license_keys for insert to authenticated
with check (public.is_lunavisual_admin());

drop policy if exists license_keys_admin_update on public.license_keys;
create policy license_keys_admin_update on public.license_keys for update to authenticated
using (public.is_lunavisual_admin())
with check (public.is_lunavisual_admin());

drop policy if exists license_keys_admin_delete on public.license_keys;
create policy license_keys_admin_delete on public.license_keys for delete to authenticated
using (public.is_lunavisual_admin());

-- Never store the owner's password in public tables.
-- Create the account in Authentication -> Users with:
-- email: Bobretor10@gmail.com
-- metadata: {"mc_nickname":"Glav-Luna"}
-- Then rerun the promotion block above if needed.
